/-
  # Base Expander for the Zig-Zag Construction

  The iterated zig-zag construction (`zigzagFamily` in `ZigZag.lean`) requires
  a concrete "seed" expander: a D-regular graph on D⁴ vertices with spectral
  gap bounded by some constant β < 1.

  The specific graph defined below was chosen by fair dice roll.
  It is guaranteed to be random.

  More precisely: a random D-regular graph on D⁴ vertices was generated
  via the configuration model (`scripts/random-graph`), its spectral gap
  was verified numerically, and it was exported as an explicit rotation map.
  The spectral gap bound is certified via an LDL^T decomposition of
  `β²D²·I - A²` (see § Certificate below).

  ## Certificate for Spectral Gap Verification

  We want to certify: `spectralGap G ≤ β`, i.e., all non-trivial eigenvalues
  λᵢ of A satisfy |λᵢ| ≤ βD. This is equivalent to `C|_{1⊥} ≽ 0` where
  `C = (βD)²·I - A²` (integer matrix when `βD ∈ ℤ`; e.g., β = 7/12, βD = 7).

  ### Certificate approaches considered

  **Dense certificates (O(n²) data, impractical for n = D⁴):**
  - LDL^T / sparse Cholesky of `C|_{1⊥}`: Random expanders have high treewidth
    (~O(n)), so Cholesky fill-in is O(n²) regardless of elimination ordering.
  - Eigenvector certificate: n rational eigenvectors × n entries each = O(n²).
  - Gram matrix: G^T G = C requires O(n²) entries in G.

  **Trace method (O(1) data, but infeasible verification):**
  - Certificate: `tr(A^{2k})` for k ≈ 91 (to get (n-1)^{1/(2k)} · max|λ| ≤ βD).
  - Verification requires computing tr(A^{2k}), which is O(n² · k) — infeasible in
    the Lean kernel for n = 20736, k = 91.
  - For small k (e.g., k = 2, walks of length 4), verification is ~n·D⁴ ≈ 4·10⁸
    comparisons (borderline feasible), but the bound is far too loose
    (gives max|λ| ≤ 40 instead of the needed ≤ 7).

  **Current approach: axioms.**
  Standard in formalization projects. The axioms are justified by numerical
  computation in Python (`scripts/random-graph`). The spectral gap can be
  verified to arbitrary precision using interval arithmetic (mpmath).

  ### Open question: algebraic base expanders
  Cayley graphs of explicit groups (e.g., SL₂(𝔽_p) with generators) have
  spectral gaps provable from representation theory rather than numerical
  computation. This would replace the axioms with a purely algebraic proof,
  but requires substantial formalization of representation theory.
-/

import AKS.RegularGraph


/-! **Base Expander Axioms** -/

/-- A concrete base expander. Currently axiomatized.

    Generated by `scripts/random-graph`; will be replaced with a concrete
    rotation map and spectral gap certificate. -/
axiom baseExpander : RegularGraph 4096 8

/-- The spectral gap of the base expander is at most 1/5.

    Will be replaced with a verified proof from the LDL^T certificate. -/
axiom baseExpander_gap : spectralGap baseExpander ≤ 1/5
