/-
  # Random 12-regular graph on 1728 vertices

  Medium test graph. Generated by `rust/compute-certificate`
  with `n=1728 d=12 seed=42 scale=2^30`.

  Regenerate data: `cargo run --release -p compute-certificate -- 1728 12 42 30 data/1728`
-/

import AKS.CertificateBridge
import AKS.NpyReader

namespace Random1728

def rotData : String := bin_base85% "data/1728/rot_map.bin"
def certData : String := bin_base85% "data/1728/cert_z.bin"

def graph : RegularGraph 1728 12 where
  rot := rotFun rotData 1728 12 (by decide) (by decide)
  rot_involution := by native_decide

theorem certificate_passes :
    checkCertificate rotData certData 1728 12 792 9 2 = true := by
  native_decide

theorem gap : spectralGap graph ≤ 10 / (1 * 12) := by
  exact_mod_cast certificate_bridge 1728 12 (by decide) (by decide) graph
    rotData certData 792 9 2 certificate_passes
    10 1 (by decide) (by decide) (fun _ => rfl)

end Random1728
