/-
  # Certificate Data Reading

  `bin_base85%` elaborator for embedding base-85 encoded `.b85` text files as
  `String` literals, plus `ensureCertificateData` for auto-generating data files.

  The `.b85` files are generated by `rust/certificate.rs` and contain base-85
  encoded i32 data (ASCII codepoints 33–117, 5 chars per i32). Since the files
  are already text, the elaborator just reads and embeds them as string literals.
-/

import Lean


/-! **Base-85 file reading** -/

/-- Read a `.b85` text file at runtime. Returns the base-85 encoded string
    for use with `decodeBase85Entry` in `CertCheck.lean`. -/
def loadBase85 (path : System.FilePath) : IO String :=
  IO.FS.readFile path

-- Term elaborator: reads a `.b85` text file at elaboration time and produces
-- a `String` literal visible to the kernel.
-- Usage: `def myData : String := bin_base85% "path/to/file.b85"`
open Lean in open Elab.Term in
elab "bin_base85% " path:str : term => do
  let content ← IO.FS.readFile ⟨path.getString⟩
  return Lean.mkStrLit content


/-! **Certificate data auto-generation** -/

/-- Ensure certificate data files exist for a given graph size.
    If `data/{n}/cert_z.b85` is missing, runs `rust/certificate.rs`
    to generate them. This is called via `#eval` before `bin_base85%` macros so
    that data files are present at elaboration time. -/
def ensureCertificateData (n d : Nat) (seed : Nat := 42) (scaleExp : Nat := 30) : IO Unit := do
  let dir : System.FilePath := s!"data/{n}"
  let certFile : System.FilePath := dir / "cert_z.b85"
  if ← certFile.pathExists then return
  IO.eprintln s!"Certificate data missing for n={n}, generating..."
  -- Ensure output directory exists
  IO.FS.createDirAll dir
  let output ← IO.Process.output {
    cmd := "cargo"
    args := #["+nightly", "-Zscript",
              "rust/certificate.rs",
              s!"{n}", s!"{d}", s!"{seed}", s!"{scaleExp}", dir.toString]
  }
  if output.exitCode != 0 then
    IO.eprintln output.stderr
    IO.eprintln output.stdout
    throw (IO.userError s!"rust/certificate.rs failed for n={n} (exit code {output.exitCode})")
  -- Verify the file was actually created
  unless ← certFile.pathExists do
    throw (IO.userError s!"rust/certificate.rs ran but {certFile} was not created")
