module
/-
  # Certificate Data Reading

  `ascii_file%` elaborator for embedding ASCII data files as `String` literals,
  plus `ensureCertificateData` for auto-generating certificate data files.

  Certificate data files (`.b85`, `.b128`) are generated by `rust/certificate.rs`
  and contain encoded integer data using only ASCII codepoints. The elaborator
  reads them via mmap and embeds the content as string literals.
-/

public import Random.Cert.ReadFFI
public import Lean
meta import Random.Cert.ReadFFI

@[expose] public section

-- Term elaborator: reads an ASCII data file at elaboration time via mmap
-- and produces a `String` literal visible to the kernel.
-- `meta import Random.Cert.ReadFFI` makes `mmapReadAscii` available in the
-- meta phase, so the elaborator (which is implicitly `meta` in module context)
-- can call the `@[extern]` C function.
-- Usage: `def myData : String := ascii_file% "path/to/file.b85"`
open Lean in open Elab.Term in
elab "ascii_file% " path:str : term => do
  let content ← mmapReadAscii path.getString
  return Lean.mkStrLit content


/-! **Certificate data auto-generation** -/

/-- Ensure certificate data files exist for a given graph size.
    If `data/{n}/cert_z.b85` is missing, first tries downloading prebuilt
    certificates via `scripts/download-certificates` (which handles its own
    locking for concurrent builds), then falls back to generating them with
    `rust/certificate.rs`. Called via `#eval` before `ascii_file%` macros so
    that data files are present at elaboration time. -/
meta def ensureCertificateData (n d : Nat) (seed : Nat := 42) (scale : Nat := 2^30)
    (useF64 : Bool := false) (useB128 : Bool := false) (useB128x5 : Bool := false)
    (c1 : Option Nat := none) : IO Unit := do
  let dir : System.FilePath := s!"data/{n}"
  let certFile : System.FilePath := dir /
    (if useB128x5 then "cert_z.b128x5" else if useB128 then "cert_z.b128" else "cert_z.b85")
  if ← certFile.pathExists then return
  -- Try downloading prebuilt certificates first (script handles locking).
  -- Don't print a message here: diagnostics are cached in .olean and replayed
  -- on every subsequent build, which would be noisy after the cert is present.
  let dl ← IO.Process.output {
    cmd := "scripts/download-certificates"
    args := #[]
  }
  if dl.exitCode == 0 && (← certFile.pathExists) then return
  -- Fall back to generating with Rust
  IO.eprintln s!"Certificate download failed for n={n}, generating locally..."
  IO.FS.createDirAll dir
  let mut args := #["+nightly", "-Zscript",
              "rust/certificate.rs",
              s!"-n={n}", s!"-d={d}", s!"--seed={seed}", s!"--scale={scale}",
              s!"--out={dir}"]
  if useF64 then args := args.push "--f64"
  if useB128x5 then args := args.push "--format=b128x5"
  else if useB128 then args := args.push "--format=b128"
  if let some c := c1 then args := args.push s!"--c1={c}"
  let output ← IO.Process.output {
    cmd := "cargo"
    args := args
  }
  if output.exitCode != 0 then
    IO.eprintln output.stderr
    IO.eprintln output.stdout
    throw (IO.userError s!"rust/certificate.rs failed for n={n} (exit code {output.exitCode})")
  unless ← certFile.pathExists do
    throw (IO.userError s!"rust/certificate.rs ran but {certFile} was not created")

end
