module
/-
  # Random 14-regular graph on 38416 = 14⁴ vertices

  Benchmark base expander for zig-zag construction with d=14.
  gcd(38416, 65536) = 16, providing a second base with small gcd relative to
  the production d=16 base.

  Generated by `rust/certificate.rs` with `n=38416 d=14 seed=42 scale=1000000000 --f64 --format=b128 --c1=520 --refine=4`.

  Regenerate data: `cargo +nightly -Zscript rust/certificate.rs -n=38416 -d=14 --seed=42 --scale=1000000000 --f64 --format=b128 --c1=520 --refine=4 --out=data/38416`
-/

public import Random.Bridge.Bridge
public import Random.Bridge.Read
public import Random.Concrete.Rot38416a
public import Random.Concrete.Rot38416b
public import Random.Concrete.Rot38416c

namespace Random38416

#eval ensureCertificateData 38416 14 (scale := 1000000000) (useF64 := true) (useB128 := true)

set_option maxHeartbeats 0 in
def rotData : String := compactToB85 (rot38416a ++ rot38416b ++ rot38416c)

set_option maxHeartbeats 0 in
def certData : String := cachedString "data/38416/cert_z.b128"

theorem involution_check : checkInvolutionSpec rotData 38416 14 = true := by
  native_decide

public def graph : RegularGraph 38416 14 where
  rot := rotFun rotData 38416 14 (by decide) (by decide)
  rot_involution :=
    checkInvolutionSpec_implies_rotFun_involution rotData 38416 14 (by decide) (by decide)
      involution_check

set_option maxHeartbeats 0 in
theorem certificate_passes :
    checkCertificateB128 rotData certData 38416 14 520 9 2 1000000000 = true := by
  native_decide

public theorem gap : spectralGap graph ≤ 1277 / (168 * 14) := by
  have h : checkCertificateSlowWith rotData (b128entry 1000000000 certData)
      38416 14 520 9 2 = true := by
    rw [← checkCertificateB128_eq_slow]; exact certificate_passes
  exact_mod_cast certificate_bridge_b128 38416 14 (by decide) (by decide) graph
    rotData certData 520 9 2 1000000000 h involution_check
    1277 168 (by decide) (by decide) (by decide) (by decide) (fun _ => rfl)

end Random38416
