module
/-
  # Random 12-regular graph on 20736 = 12⁴ vertices

  Production base expander for the zig-zag construction.
  Generated by `rust/certificate.rs` with `n=20736 d=12 seed=42 scale=2000000000 --f64 --format=b128`.

  Regenerate data: `cargo +nightly -Zscript rust/certificate.rs -n=20736 -d=12 --seed=42 --scale=2000000000 --f64 --format=b128 --out=data/20736`
-/

public import Random.Bridge.Bridge
public import Random.Bridge.Read
public import Random.Concrete.Rot20736a
public import Random.Concrete.Rot20736b
public import Random.Concrete.Rot20736c

namespace Random20736

#eval ensureCertificateData 20736 12 (scale := 2000000000) (useF64 := true) (useB128 := true)

set_option maxHeartbeats 0 in
def rotData : String := compactToB85 (rot20736a ++ rot20736b ++ rot20736c)

set_option maxHeartbeats 0 in
def certData : String := ascii_file% "data/20736/cert_z.b128"

theorem involution_check : checkInvolutionSpec rotData 20736 12 = true := by
  native_decide

public def graph : RegularGraph 20736 12 where
  rot := rotFun rotData 20736 12 (by decide) (by decide)
  rot_involution :=
    checkInvolutionSpec_implies_rotFun_involution rotData 20736 12 (by decide) (by decide)
      involution_check

set_option maxHeartbeats 0 in
theorem certificate_passes :
    checkCertificateB128 rotData certData 20736 12 792 9 2 2000000000 = true := by
  native_decide

public theorem gap : spectralGap graph ≤ 197 / (21 * 12) := by
  have h : checkCertificateSlowWith rotData (b128entry 2000000000 certData)
      20736 12 792 9 2 = true := by
    rw [← checkCertificateB128_eq_slow]; exact certificate_passes
  exact_mod_cast certificate_bridge_b128 20736 12 (by decide) (by decide) graph
    rotData certData 792 9 2 2000000000 h involution_check
    197 21 (by decide) (by decide) (by decide) (by decide) (fun _ => rfl)

end Random20736
