module
/-
  # Random 16-regular graph on 65536 = 16⁴ = 2¹⁶ vertices

  Base expander for the power-of-2 zig-zag construction. D=16 gives
  B = D⁴ = 2¹⁶, so all zigzag family sizes B^(k+1) are powers of 2.
  Contracting to any power-of-2 target m gives equal fibers → regular graphs.

  The spectral gap bound β = 17/32 = 0.53125 satisfies the
  convergence condition β < 1/√3 for the RVW fixed-point iteration.

  Generated by `rust/certificate.rs` with `n=65536 d=16 seed=42 scale=2100000000 --f64 --format=b128x5 --c1=650 --refine=4`.

  Regenerate data: `cargo +nightly -Zscript rust/certificate.rs -n=65536 -d=16 --seed=42 --scale=2100000000 --f64 --format=b128x5 --c1=650 --refine=4 --out=data/65536`
-/

public import Random.Bridge.Bridge
public import Random.Bridge.Read

namespace Random65536

#eval ensureCertificateData 65536 16 (scale := 2100000000) (useF64 := true) (useB128x5 := true) (c1 := some 650)

def rotData : String := cachedString "data/65536/rot_map.b85"
def certData : String := cachedString "data/65536/cert_z.b128x5"

theorem involution_check : checkInvolutionSpec rotData 65536 16 = true := by
  native_decide

public def graph : RegularGraph 65536 16 where
  rot := rotFun rotData 65536 16 (by decide) (by decide)
  rot_involution :=
    checkInvolutionSpec_implies_rotFun_involution rotData 65536 16 (by decide) (by decide)
      involution_check

set_option maxHeartbeats 0 in
theorem certificate_passes :
    checkCertificateB128x5 rotData certData 65536 16 650 9 2 2100000000 = true := by
  native_decide

public theorem gap : spectralGap graph ≤ 17 / (2 * 16) := by
  have h : checkCertificateSlowWith rotData (b128x5entry 2100000000 certData)
      65536 16 650 9 2 = true := by
    rw [← checkCertificateB128x5_eq_slow]; exact certificate_passes
  exact_mod_cast certificate_bridge_b128x5 65536 16 (by decide) (by decide) graph
    rotData certData 650 9 2 2100000000 h involution_check
    17 2 (by decide) (by decide) (by decide) (by decide) (fun _ => rfl)

end Random65536
