/-
  # Random 12-regular graph on 1728 vertices

  Medium test graph. Generated by `rust/certificate.rs`
  with `n=1728 d=12 seed=42 scale=2^30`.

  Regenerate data: `cargo +nightly -Zscript rust/certificate.rs 1728 12 42 30 data/1728`
-/

import AKS.Cert.Bridge
import AKS.Cert.Read

namespace Random1728

#eval ensureCertificateData 1728 12

def rotData : String := bin_base85% "data/1728/rot_map.b85"
def certData : String := bin_base85% "data/1728/cert_z.b85"

theorem involution_check : checkInvolutionSpec (rotData.toUTF8) 1728 12 = true := by
  native_decide

def graph : RegularGraph 1728 12 where
  rot := rotFun rotData 1728 12 (by decide) (by decide)
  rot_involution :=
    checkInvolutionSpec_implies_rotFun_involution rotData 1728 12 (by decide) (by decide)
      involution_check

theorem certificate_passes :
    checkCertificate rotData certData 1728 12 792 9 2 = true := by
  native_decide

theorem gap : spectralGap graph ≤ 10 / (1 * 12) := by
  have h : checkCertificateSlow rotData certData 1728 12 792 9 2 = true := by
    rw [← checkCertificate_eq_slow]; exact certificate_passes
  exact_mod_cast certificate_bridge 1728 12 (by decide) (by decide) graph
    rotData certData 792 9 2 h involution_check
    10 1 (by decide) (by decide) (by decide) (by decide) (fun _ => rfl)

end Random1728
