/-
  # Random 12-regular graph on 20736 = 12⁴ vertices

  Production base expander for the zig-zag construction.
  Generated by `rust/certificate.rs` with `n=20736 d=12 seed=42 scale=2^30`.

  Regenerate data: `cargo +nightly -Zscript rust/certificate.rs 20736 12 42 30 data/20736`

  The certificate (821 MB cert_z.bin) is too large to embed as a string literal
  on a 16 GB machine. The rot_map (1.9 MB) and involution check work fine; only
  the PSD certificate check is sorry'd pending a machine with more RAM.
-/

import AKS.Cert.Bridge
import AKS.Cert.FastProof
import AKS.Cert.Read

namespace Random20736

#eval ensureCertificateData 20736 12

set_option maxHeartbeats 0 in
def rotData : String := bin_base85% "data/20736/rot_map.bin"

-- Certificate data too large (821 MB) for string literal on 16 GB machine
-- def certData : String := bin_base85% "data/20736/cert_z.bin"
axiom certData : String

theorem involution_check : checkInvolutionSpec (rotData.toUTF8) 20736 12 = true := by
  native_decide

def graph : RegularGraph 20736 12 where
  rot := rotFun rotData 20736 12 (by decide) (by decide)
  rot_involution :=
    checkInvolutionSpec_implies_rotFun_involution rotData 20736 12 (by decide) (by decide)
      involution_check

theorem certificate_passes :
    checkCertificateFast rotData certData 20736 12 792 9 2 = true := by
  sorry

theorem gap : spectralGap graph ≤ 10 / (1 * 12) := by
  have h : checkCertificateSlow rotData certData 20736 12 792 9 2 = true := by
    rw [← checkCertificateFast_eq_slow]; exact certificate_passes
  exact_mod_cast certificate_bridge 20736 12 (by decide) (by decide) graph
    rotData certData 792 9 2 h involution_check
    10 1 (by decide) (by decide) (by decide) (by decide) sorry

end Random20736
