/-
  # Random 4-regular graph on 16 vertices

  Small test graph for fast iteration. Generated by `rust/certificate.rs`
  with `n=16 d=4 seed=42 scale=2^30`.

  Regenerate data: `cargo +nightly -Zscript rust/certificate.rs 16 4 42 30 data/16`
-/

import AKS.CertificateBridge
import AKS.NpyReader

namespace Random16

#eval ensureCertificateData 16 4

def rotData : String := bin_base85% "data/16/rot_map.bin"
def certData : String := bin_base85% "data/16/cert_z.bin"

theorem involution_check : checkInvolutionSpec (rotData.toUTF8) 16 4 = true := by
  native_decide

def graph : RegularGraph 16 4 where
  rot := rotFun rotData 16 4 (by decide) (by decide)
  rot_involution :=
    checkInvolutionSpec_implies_rotFun_involution rotData 16 4 (by decide) (by decide)
      involution_check

theorem certificate_passes :
    checkCertificate rotData certData 16 4 216 9 1 = true := by
  native_decide

theorem gap : spectralGap graph ≤ 5 / (1 * 4) := by
  exact_mod_cast certificate_bridge 16 4 (by decide) (by decide) graph
    rotData certData 216 9 1 certificate_passes
    5 1 (by decide) (by decide) (by decide) (by decide) (fun _ => rfl)

end Random16
